---
master_host: "{{ hostvars[groups['terraform_jenkins_master'][0]]['ansible_host'] }}"
slave_agent_name: "{{ inventory_hostname }}"
slave_linux_jenkins_cred_id: new_cred
slave_linux_jenkins_username: new_user
slave_linux_jenkins_public_key:
