---
- name: Install jenkins master node
  hosts: terraform_jenkins_master
  become: true
  roles:
    - name: geerlingguy.java
    - name: geerlingguy.jenkins
  tasks:
    - name: Copy ssh keys
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: 0600
        owner: jenkins
        group: jenkins
      with_items:
        - src: '../.ssh/id_rsa'
          dest: '/home/jenkins/.ssh/id_rsa'
        - src: '../.ssh/id_rsa.pub'
          dest: '/home/jenkins/.ssh/id_rsa.pub'
  tags: master

- name: Install jenkins slave node
  hosts: terraform_jenkins_slave
  become: true
  roles:
    - name: geerlingguy.java
    - name: lean_delivery.jenkins_slave
  tags: slave
